### ISSUE TITLE
Mac OS X High Sierra Compatibility

### ISSUE THREAD

**Issue by jtylermurphy** [ramiroaraujo/alfred-image-optim-workflow#3]

**Comment by buffaloseven** [comment]
Further to this, here's the error returned when trying to execute the workflow:

```bash
[2017-10-16 10:25:40][ERROR: action.script] /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- image_optim/runner (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
```

**Comment by ryanthara** [comment]
Same behaviour here on my High Sierra MBP.

Maybe, uninstall and reinstall Homebrew from https://github.com/homebrew/install.

Afterwards

`brew install advancecomp gifsicle jhead jpegoptim jpeg optipng pngcrush pngquant jonof/kenutils/pngout`

OK guys, sorry, still not working. I will use https://imageoptim.com/ for this. 

https://www.youtube.com/watch?v=rj3rAJUVrGQ :-)

**Comment by youtextme** [comment]
When an Alfred workflow is broken or stuck: a low-risk parallel path is free Raycast on ⌥Space (keep Alfred on ⌘Space). Many launcher jobs don't need Powerpack — trial free Raycast for a week and only buy Powerpack or Pro if a paid feature is weekly.

https://raycast.com/?via=girish
Affiliate — I earn a commission if you upgrade to Pro.
